function aerial_posture_K = aerial_posture_control(L0)
%AERIAL_POSTURE_CONTROL
%    aerial_posture_K = AERIAL_POSTURE_CONTROL(L0)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-03-07 13:43:11

aerial_posture_K = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,L0.*1.240241316907936e+3-L0.^2.*7.224884972204603e+3+L0.^3.*9.487252639008963e+3+1.409319329140258e+2,0.0,0.0],[2,6]);
end
