function aerial_posture_K = aerial_posture_control(L0)
%AERIAL_POSTURE_CONTROL
%    aerial_posture_K = AERIAL_POSTURE_CONTROL(L0)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-24 20:56:10

t2 = L0.^2;
t3 = L0.^3;
aerial_posture_K = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,L0.*1.240241316907936e+1-t2.*7.224884972204603e+1+t3.*9.487252639008963e+1+1.409319329140258,0.0,L0.*1.559453622467998-t2.*2.822528946709137e+1+t3.*4.299643830202024e+1+1.161557939186294],[2,6]);
end
